### ISSUE TITLE
Fixing postgres auth error

### ISSUE THREAD

**Issue by mosdevly** [srijan4friends/carapp#1]
https://github.com/srijan4friends/carapp/blob/cfa77de0e6c3191f5786a0cf1d7889765e406b23/docker-compose.yml#L6

After looking at it with fresh eyes I see the error. A couple things we did wrong:

1. I wasn't able to see if you were removing the images/containers/volumes each time we exited the servers. So I suspect you may have been reusing the same images after each config update -- you have to rebuild and Docker will reuse the old user/password combos.
2. To define a password for `postgres` user, just add a password. No need to add a POSTGRES_USER (on the postgres service).

The default user for PostgreSQL is `postgres` with no password. This user is used by default so if your app will use this user, add `POSTGRES_PASSWORD` in your `docker-compose.yml`. Update `application.properties` with the username/password.

```
# in application.properties
spring.datasource.password=notsecure
spring.datasource.username=speedy

# in docker-compose.yml
version: "3"
services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: speedy
      POSTGRES_PASSWORD: notsecure
      POSTGRES_DB: carapp_db
  carapp:
    build: .
    environment:
      DB_HOST: postgresdb
      DB_USER: speedy
      DB_PASSWORD: notsecure
      DB_NAME: carapp_db
    depends_on:
      - postgresdb
    ports:
      - "5432:5432"

volumes:
  carapp_volume: {}
```

1. Be sure you remove all old containers and images for a fresh start.
2. Remove old volumes because docker will reuse it, leading to a repeat of the auth errors.
3. Update your config files with the users/passwords you'll use
4. `docker-compose up`
